<?php

namespace DoctrineORMModule\Proxy\__CG__\OrdemServico\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrdemServico extends \OrdemServico\Entity\OrdemServico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id_ordem_servico', 'nu_ordem_servico', 'ds_contrato', 'ds_nome', 'ds_justificativa', 'dt_prazo', 'ds_impedimento_execucao', 'ds_sugestao_melhoria', 'no_fiscal_requisitante', 'no_fiscal_tecnico', 'dt_emissao', 'no_gestor_contrato', 'dt_recepcao', 'no_preposto', 'ds_svn', 'tp_situacao', 'ds_descricao', 'id_usuario_alteracao', 'dt_alteracao');
        }

        return array('__isInitialized__', 'id_ordem_servico', 'nu_ordem_servico', 'ds_contrato', 'ds_nome', 'ds_justificativa', 'dt_prazo', 'ds_impedimento_execucao', 'ds_sugestao_melhoria', 'no_fiscal_requisitante', 'no_fiscal_tecnico', 'dt_emissao', 'no_gestor_contrato', 'dt_recepcao', 'no_preposto', 'ds_svn', 'tp_situacao', 'ds_descricao', 'id_usuario_alteracao', 'dt_alteracao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrdemServico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOrdemServico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOrdemServico', array());

        return parent::getIdOrdemServico();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdOrdemServico($intIdOrdemServico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdOrdemServico', array($intIdOrdemServico));

        return parent::setIdOrdemServico($intIdOrdemServico);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuOrdemServico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuOrdemServico', array());

        return parent::getNuOrdemServico();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuOrdemServico($intNuOrdemServico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuOrdemServico', array($intNuOrdemServico));

        return parent::setNuOrdemServico($intNuOrdemServico);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsContrato', array());

        return parent::getDsContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsContrato($strDsContrato = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsContrato', array($strDsContrato));

        return parent::setDsContrato($strDsContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsNome', array());

        return parent::getDsNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsNome($strDsNome = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsNome', array($strDsNome));

        return parent::setDsNome($strDsNome);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsJustificativa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsJustificativa', array());

        return parent::getDsJustificativa();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsJustificativa($strDsJustificativa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsJustificativa', array($strDsJustificativa));

        return parent::setDsJustificativa($strDsJustificativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtPrazo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtPrazo', array());

        return parent::getDtPrazo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtPrazo($strDtPrazo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtPrazo', array($strDtPrazo));

        return parent::setDtPrazo($strDtPrazo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoFiscalRequisitante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoFiscalRequisitante', array());

        return parent::getNoFiscalRequisitante();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoFiscalRequisitante($strNoFiscalRequisitante = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoFiscalRequisitante', array($strNoFiscalRequisitante));

        return parent::setNoFiscalRequisitante($strNoFiscalRequisitante);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoFiscalTecnico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoFiscalTecnico', array());

        return parent::getNoFiscalTecnico();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoFiscalTecnico($strNoFiscalTecnico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoFiscalTecnico', array($strNoFiscalTecnico));

        return parent::setNoFiscalTecnico($strNoFiscalTecnico);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtEmissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtEmissao', array());

        return parent::getDtEmissao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtEmissao($strDtEmissao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtEmissao', array($strDtEmissao));

        return parent::setDtEmissao($strDtEmissao);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoGestorContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoGestorContrato', array());

        return parent::getNoGestorContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoGestorContrato($strNoGestorContrato = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoGestorContrato', array($strNoGestorContrato));

        return parent::setNoGestorContrato($strNoGestorContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtRecepcao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtRecepcao', array());

        return parent::getDtRecepcao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtRecepcao($strDtRecepcao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtRecepcao', array($strDtRecepcao));

        return parent::setDtRecepcao($strDtRecepcao);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoPreposto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoPreposto', array());

        return parent::getNoPreposto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoPreposto($strNoPreposto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoPreposto', array($strNoPreposto));

        return parent::setNoPreposto($strNoPreposto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsSvn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsSvn', array());

        return parent::getDsSvn();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsSvn($strDsSvn = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsSvn', array($strDsSvn));

        return parent::setDsSvn($strDsSvn);
    }

    /**
     * {@inheritDoc}
     */
    public function getTpSituacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpSituacao', array());

        return parent::getTpSituacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setTpSituacao($intTpSituacao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpSituacao', array($intTpSituacao));

        return parent::setTpSituacao($intTpSituacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsImpedimentoExecucao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsImpedimentoExecucao', array());

        return parent::getDsImpedimentoExecucao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsImpedimentoExecucao($ds_impedimento_execucao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsImpedimentoExecucao', array($ds_impedimento_execucao));

        return parent::setDsImpedimentoExecucao($ds_impedimento_execucao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsSugestaoMelhoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsSugestaoMelhoria', array());

        return parent::getDsSugestaoMelhoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsSugestaoMelhoria($ds_sugestao_melhoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsSugestaoMelhoria', array($ds_sugestao_melhoria));

        return parent::setDsSugestaoMelhoria($ds_sugestao_melhoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsDescricao', array());

        return parent::getDsDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsDescricao($ds_descricao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsDescricao', array($ds_descricao));

        return parent::setDsDescricao($ds_descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricaoOrdemServico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricaoOrdemServico', array());

        return parent::getDescricaoOrdemServico();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuarioAlteracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuarioAlteracao', array());

        return parent::getIdUsuarioAlteracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuarioAlteracao($id_usuario_alteracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuarioAlteracao', array($id_usuario_alteracao));

        return parent::setIdUsuarioAlteracao($id_usuario_alteracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtAlteracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtAlteracao', array());

        return parent::getDtAlteracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtAlteracao($dt_alteracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtAlteracao', array($dt_alteracao));

        return parent::setDtAlteracao($dt_alteracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute($strAttribute = NULL, $strType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', array($strAttribute, $strType));

        return parent::getAttribute($strAttribute, $strType);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($strAttribute = NULL, $mixValue = NULL, $strType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', array($strAttribute, $mixValue, $strType));

        return parent::setAttribute($strAttribute, $mixValue, $strType);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $arrAttributeNotIn = array (
), $mixEntity = NULL, $intDeep = 0, $intMaxDeep = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($arrAttributeNotIn, $mixEntity, $intDeep, $intMaxDeep));

        return parent::toArray($arrAttributeNotIn, $mixEntity, $intDeep, $intMaxDeep);
    }

    /**
     * {@inheritDoc}
     */
    public function convertToIndicator($mixValue = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'convertToIndicator', array($mixValue));

        return parent::convertToIndicator($mixValue);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($strFunction, $arrArgument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($strFunction, $arrArgument));

        return parent::__call($strFunction, $arrArgument);
    }

}
