<?php

namespace DoctrineORMModule\Proxy\__CG__\OrdemServico\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CatalogoServico extends \OrdemServico\Entity\CatalogoServico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id_catalogo_servico', 'no_catalogo_servico', 'area_assessoria');
        }

        return array('__isInitialized__', 'id_catalogo_servico', 'no_catalogo_servico', 'area_assessoria');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CatalogoServico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCatalogoServico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCatalogoServico', array());

        return parent::getIdCatalogoServico();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCatalogoServico($intIdCatalogoServico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCatalogoServico', array($intIdCatalogoServico));

        return parent::setIdCatalogoServico($intIdCatalogoServico);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCatalogoServico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCatalogoServico', array());

        return parent::getNoCatalogoServico();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCatalogoServico($strNoCatalogoServico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCatalogoServico', array($strNoCatalogoServico));

        return parent::setNoCatalogoServico($strNoCatalogoServico);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaAssessoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaAssessoria', array());

        return parent::getAreaAssessoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaAssessoria($strAreaAssessoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaAssessoria', array($strAreaAssessoria));

        return parent::setAreaAssessoria($strAreaAssessoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute($strAttribute = NULL, $strType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', array($strAttribute, $strType));

        return parent::getAttribute($strAttribute, $strType);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($strAttribute = NULL, $mixValue = NULL, $strType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', array($strAttribute, $mixValue, $strType));

        return parent::setAttribute($strAttribute, $mixValue, $strType);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $arrAttributeNotIn = array (
), $mixEntity = NULL, $intDeep = 0, $intMaxDeep = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($arrAttributeNotIn, $mixEntity, $intDeep, $intMaxDeep));

        return parent::toArray($arrAttributeNotIn, $mixEntity, $intDeep, $intMaxDeep);
    }

    /**
     * {@inheritDoc}
     */
    public function convertToIndicator($mixValue = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'convertToIndicator', array($mixValue));

        return parent::convertToIndicator($mixValue);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($strFunction, $arrArgument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($strFunction, $arrArgument));

        return parent::__call($strFunction, $arrArgument);
    }

}
