<?php

namespace DoctrineORMModule\Proxy\__CG__\OrdemServico\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \OrdemServico\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'st_ativo', 'id_usuario', 'no_usuario', 'nu_pis', 'ds_email', 'ds_login', 'tp_vinculo', 'in_ativo', 'ds_hash_apex', 'ds_senha');
        }

        return array('__isInitialized__', 'st_ativo', 'id_usuario', 'no_usuario', 'nu_pis', 'ds_email', 'ds_login', 'tp_vinculo', 'in_ativo', 'ds_hash_apex', 'ds_senha');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($id_usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($id_usuario));

        return parent::setIdUsuario($id_usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoUsuario', array());

        return parent::getNoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoUsuario($no_usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoUsuario', array($no_usuario));

        return parent::setNoUsuario($no_usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuPis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuPis', array());

        return parent::getNuPis();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuPis($nu_pis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuPis', array($nu_pis));

        return parent::setNuPis($nu_pis);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsEmail', array());

        return parent::getDsEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsEmail($ds_email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsEmail', array($ds_email));

        return parent::setDsEmail($ds_email);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsLogin', array());

        return parent::getDsLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsLogin($ds_login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsLogin', array($ds_login));

        return parent::setDsLogin($ds_login);
    }

    /**
     * {@inheritDoc}
     */
    public function getInAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInAtivo', array());

        return parent::getInAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setInAtivo($in_ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInAtivo', array($in_ativo));

        return parent::setInAtivo($in_ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTpVinculo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpVinculo', array());

        return parent::getTpVinculo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTpVinculo($tp_vinculo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpVinculo', array($tp_vinculo));

        return parent::setTpVinculo($tp_vinculo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsHashApex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsHashApex', array());

        return parent::getDsHashApex();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsHashApex($ds_hash_apex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsHashApex', array($ds_hash_apex));

        return parent::setDsHashApex($ds_hash_apex);
    }

    /**
     * {@inheritDoc}
     */
    public function getStAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAtivo', array());

        return parent::getStAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAtivo($st_ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAtivo', array($st_ativo));

        return parent::setStAtivo($st_ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsSenha', array());

        return parent::getDsSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsSenha($ds_senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsSenha', array($ds_senha));

        return parent::setDsSenha($ds_senha);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute($strAttribute = NULL, $strType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', array($strAttribute, $strType));

        return parent::getAttribute($strAttribute, $strType);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($strAttribute = NULL, $mixValue = NULL, $strType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', array($strAttribute, $mixValue, $strType));

        return parent::setAttribute($strAttribute, $mixValue, $strType);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $arrAttributeNotIn = array (
), $mixEntity = NULL, $intDeep = 0, $intMaxDeep = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($arrAttributeNotIn, $mixEntity, $intDeep, $intMaxDeep));

        return parent::toArray($arrAttributeNotIn, $mixEntity, $intDeep, $intMaxDeep);
    }

    /**
     * {@inheritDoc}
     */
    public function convertToIndicator($mixValue = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'convertToIndicator', array($mixValue));

        return parent::convertToIndicator($mixValue);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($strFunction, $arrArgument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($strFunction, $arrArgument));

        return parent::__call($strFunction, $arrArgument);
    }

}
