<?php
$strTitle = 'Administração de Atividades';
$this->headTitle($strTitle);
?>
<h1><?php echo $this->escapeHtml($strTitle); ?></h1>
<p>Realize a administração das atividades.</p>
<?php
$this->angular()
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/AtividadeService'), 'dependence' => 'Service/AbstractService'))
    ->addController(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/AtividadeController'), 'dependence' => 'Controller/AbstractGridController', 'html' => $this->form()->render($this->form))); 
?>