<?php
$strTitle = 'Administração de Ordens de Serviço';
$this->headTitle($strTitle);
?>
<link href="<?php echo $this->basePath() . getRenderScriptUrl('InepSkeleton/OrdemServico/css/grid'); ?>" rel="stylesheet" type="text/css">
<h1><?php echo $this->escapeHtml($strTitle); ?></h1>
<p>Realize a administração das ordens de serviço.</p>
<?php
$this->angular()
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/OrdemServicoService'), 'dependence' => 'Service/AbstractService'))
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/OrdemServicoAceiteService'), 'dependence' => 'Service/AbstractService'))
    ->addController(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/OrdemServicoController'), 'dependence' => 'Controller/AbstractGridController', 'html' => $this->form()->render($this->form)));
?>
<script
    type="text/javascript"
    src="<?= $this->basePath() . '/js_entityconst/OrdemServico/OrdemServico'; ?>">
</script>
<script
    type="text/javascript"
    src="<?php echo $this->basePath() . '/js_message/OrdemServico'; ?>">
</script>
