<?php
$strTitle = 'Catálogo de Serviço';
$this->headTitle($strTitle);
?>
<h1><?php echo $this->escapeHtml($strTitle); ?></h1>
<p>Insira as devidas informações e observe o símbolo <font style="color: red;">*</font> para aquelas entradas de dados que são de preenchimento obrigatório.</p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('catologoservico', array('action' => 'add')));
$this->angular()
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/CatalogoService'), 'dependence' => 'Service/AbstractService'))
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/AtividadeService'), 'dependence' => 'Service/AbstractService'))
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/CatalogoServicoAtividade'), 'dependence' => 'Service/AbstractService'))
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/DemandaService'), 'dependence' => 'Service/AbstractService'))
    ->addController(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/CatalogoFormController'), 'dependence' => 'Controller/AbstractGridController', 'html' => $this->form()->render($this->form)));
?>