<?php
$strTitle = 'Relatório de Faturamento';
$this->headTitle($strTitle);
?>
<h1><?php echo $this->escapeHtml($strTitle); ?></h1>
<p>Realize geração do relatório de faturamento referente as OS que estão com situação emitida.</p>
<?php
$this->angular()
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/RelatorioFaturamentoService'), 'dependence' => 'Service/AbstractService'))
    ->addController(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/RelatorioFaturamentoFormController'), 'dependence' => 'Controller/AbstractGridController', 'html' => $this->form()->render($form)));
?>