<?php
$strTitle = 'Administração de Usuário';
$this->headTitle($strTitle);
?>
    <h1><?php echo $this->escapeHtml($strTitle); ?></h1>
    <p>Edite as informações necessárias e observe o símbolo <font style="color: red;">*</font> para aquelas entradas de
        dados que são de preenchimento obrigatório.</p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('usuario', array('action' => 'edit', 'id_usuario' => $form->get('id_usuario')->getValue())));
$this->angular()
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/UsuarioService'), 'dependence' => 'Service/AbstractService'))
    ->addController(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/UsuarioFormController'), 'dependence' => 'Controller/AbstractFormController', 'html' => $this->form()->render($form)));
?>