<?php
$strTitle = 'Administração de Demandas';
$this->headTitle($strTitle);
?>
<h1><?php echo $this->escapeHtml($strTitle); ?></h1>
<p>Realize a administração das demandas.</p>
<?php
$this->angular()
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/DemandaService'), 'dependence' => 'Service/AbstractService'))
    ->addController(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/DemandaController'), 'dependence' => 'Controller/AbstractGridController', 'html' => $this->form()->render($this->form)))
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/OrdemServicoDemandaService'), 'dependence' => 'Service/AbstractService'));;
?>