<?php
$strTitle = 'Relatório de Desempenho Individual';
$this->headTitle($strTitle);
?>
<h1><?php echo $this->escapeHtml($strTitle); ?></h1>
<p>Funcionalidade responsável por gerar o relatório de desempenho individual.</p>
<?php
$this->angular()
    ->addService(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/RelatorioPessoalService'), 'dependence' => 'Service/AbstractService'))
    ->addController(array('url' => getRenderScriptUrl('InepSkeleton/OrdemServico/js/RelatorioPessoalFormController'), 'dependence' => 'Controller/AbstractGridController', 'html' => $this->form()->render($form)));
?>