INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (1, 'Ualison Aguiar da Ponte Frota', '013558020277', 'ualison.frota@datainfo.inf.br', 'ualison.frota');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (2, 'Carlos Massashi Utiumi', '012903255506', 'carlos.utiumi@datainfo.inf.br', 'carlos.utiumi');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (3, 'Carolina Maia Aichinger', '014569555272', 'carolina.aichinger@datainfo.inf.br', 'carolina.aichinger');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (4, 'Cristiano da Silva Melo', '018111351998', 'cristiano.melo@datainfo.inf.br', 'cristiano.melo');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (5, 'Fabiano Shidaka Maeda', '020052767188', 'fabiano.maeda@datainfo.inf.br', 'fabiano.maeda');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (6, 'Gilvan Ornelas Fernandes Filho', '015508271272', 'gilvan.filho@datainfo.inf.br', 'gilvan.filho');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (7, 'Jackelyne Cavalcante Nascimento Borges', '012628603448', 'jackelyne.borges@datainfo.inf.br', 'jackelyne.borges');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (8, 'Jonathans Camilo Coelho de Sousa', '020318282172', 'jonathans.coelho@datainfo.inf.br', 'jonathans.coelho');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (9, 'Leticia Ramos Reinaldi', '015215810277', 'leticia.reinaldi@datainfo.inf.br', 'leticia.reinaldi');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (10, 'Lucia Carvalho Horta', '012088993667', 'lucia.horta@datainfo.inf.br', 'lucia.horta');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (11, 'Luciana Goncalves Chaves Barros', '012613208270', 'luciana.barros@datainfo.inf.br', 'luciana.barros');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (12, 'Marcelo Henrique Felipe', '012662535514', 'marcelo.felipe@datainfo.inf.br', 'marcelo.henrique');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (13, 'Paulo Eduardo Costa Oliveira', '013514846277', 'paulo.oliveira@datainfo.inf.br', 'pauloe.costa');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (14, 'Rafael Gomes Moreira', '012886029094', 'rafael.moreira@datainfo.inf.br', 'rafael.moreira');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (15, 'Raphael de Sousa Cruz', '013100216279', 'raphael.sousa@datainfo.inf.br', 'raphael.sousa');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (16, 'Rebert Richards Cruz de Freitas', '013163438279', 'rebert.freitas@datainfo.inf.br', 'rebert.freitas');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (17, 'Sandro Araújo Dantas', '012398005579', 'sandro.dantas@datainfo.inf.br', 'sandro.dantas');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (18, 'Sérgio Luciano Soares Gaião', '012706156270', 'sergio.soares@datainfo.inf.br', 'sergio.gaiao');
INSERT INTO tb_usuario (id_usuario, no_usuario, nu_pis, ds_email, ds_login) VALUES (19, 'Thiago Lenin Sousa Silva Batista', '020430631337', 'thiago.lenin@datainfo.inf.br', 'thiago.lenin');