<?php

use InepZend\Util\Server;
use InepZend\Util\Date;

$renderDescricaoDemanda = $this->renderDescricaoDemandaHelper();
?>
    <head>
        <meta http-equiv="cache-control" content="max-age=0"/>
        <meta http-equiv="cache-control" content="no-cache"/>
        <meta http-equiv="expires" content="0"/>
        <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT"/>
        <meta http-equiv="pragma" content="no-cache"/>
        <meta charset="UTF-8">
    </head>
    <style>
        table {
            border-spacing: 0;
            border-collapse: collapse;
        }

        .lista-demanda li span {
            font-weight: normal;
        }

        td, th, div, p {
            font-size: 12px;
        }

        td, th {
            border: 1px solid black;
        }

        .sem-borda {
            border: 0px !important;
        }

        body {
            margin: 0px;
        }

        .page {
            width: 1000px;
            background-color: #FFFFFF;
            text-align: left;
            margin-bottom: 20px;
            padding: 10px;
        }
    </style>
    <div class="page">
        <table style="width: 100%;">
            <tr>
                <td class="brasao sem-borda" align="center"><img
                        src="<?php echo Server::getHost(true) . '/vendor/InepZend/images/brasaoNacional2.jpg'; ?>"
                        style="height: 100px;"></td>
            </tr>
            <tr>
                <td class="sem-borda" align="center"><strong>Ministério da Educação</strong></td>
            </tr>
            <tr>
                <td class="sem-borda" align="center"><strong>Instituto Nacional de Estudos e Pesquisas Educacionais
                        Anísio Teixeira</strong></td>
            </tr>
            <tr>
                <td class="sem-borda" align="center"><strong>Diretoria de Tecnologia e Disseminação de Informações
                        Educacionais</strong></td>
            </tr>
            <tr>
                <td class="sem-borda"></td>
            </tr>
            <tr>
                <td class="sem-borda"></td>
            </tr>
            <tr>
                <td class="sem-borda" align="center"><strong>RELATÓRIO DE EXECUÇÃO DE SERVIÇO</strong></td>
            </tr>
        </table>
        <br/>
        <table style="width: 100%;" cellpadding="3" cellspacing="1">
            <tr>
                <td><strong>Contrato: </strong><?php echo $this->ordem_servico->getDsContrato(); ?></td>
                <td>Referente à Ordem de Serviço Nº <?php echo $this->ordem_servico->getNuOrdemServico(); ?></td>
                <td>
                    <p>Data: <?php echo Date::convertDate($this->ordem_servico->getDtPrazo(), 'd/m/Y'); ?></p>

                    <p>Hora: <?php echo Date::convertDate($this->ordem_servico->getDtPrazo(), 'H:i'); ?></p>
                </td>
            </tr>
        </table>
        <table style="width: 100%;" cellpadding="3" cellspacing="1">
            <tr style="background: #CCCCCC">
                <td colspan="3" align="center">
                    <strong>Detalhamento da Execução das Atividades</strong>
                </td>
            </tr>
            <tr>
                <td align="center" style="width: 0px;"><strong>Nº</strong></td>
                <td align="center"><strong>DESCRIÇÃO</strong></td>
                <td align="center" style="width: 0px;"><strong>Tempo</strong></td>
            </tr>
            <?php
            foreach ($this->arrDemandas as $mixDemanda) :
                $intPosicao = $mixDemanda['demanda']->sequencia;
                if ($mixDemanda['demanda']->getIdDemandaSuperior()) :
                    foreach ($mixDemanda['atividade'] as $intSequencia => $arrAtividade) :
                        ?>
                        <tr>
                            <td><?php echo $intPosicao . '.' . $arrAtividade['nu_sequencia']; ?></td>
                            <td>
                                <?php echo $mixDemanda['demanda']->getNoDemanda(); ?>
                                <br/>
                                <?php echo $renderDescricaoDemanda->renderizaDescricaoImpressao($mixDemanda['demanda']->getDsDescricao()); ?>
                            </td>
                            <td>
                                <?php
                                echo number_format($arrAtividade['vl_qma']) . ' hs';
                                ?>
                            </td>
                        </tr>
                        <?php
                    endforeach;
                else :?>
                    <tr>
                        <td><?php echo $intPosicao; ?></td>
                        <td>
                            <?php echo $mixDemanda['demanda']->getNoDemanda(); ?>
                            <br/>
                            <?php echo $renderDescricaoDemanda->renderizaDescricaoImpressao($mixDemanda['demanda']->getDsDescricao()); ?>
                        </td>
                        <td>
                            <?php
                            $intHoraExecutada = ceil($mixDemanda['demanda']->hora_execucao);
                            echo (($intHoraExecutada < 1) ? 1 : $intHoraExecutada) . ' hs';
                            ?>
                        </td>
                    </tr>
                    <?php
                endif;
            endforeach;
            ?>
            <tr>
                <td align="center"><?php echo($intPosicao + 1); ?></td>
                <td><?php echo $this->ordem_servico->getDsSvn(); ?></td>
                <td align="center">1h</td>
            </tr>
        </table>
        <br/>
        <table style="width: 100%;" cellpadding="3" cellspacing="1">
            <tr style="background: #CCCCCC">
                <td colspan="3" align="center">
                    <strong>Impedimentos de Execução</strong>
                </td>
            </tr>
            <tr>
                <td colspan="3" align="left">
                    <?php echo ($this->ordem_servico->getDsImpedimentoExecucao()) ? $this->ordem_servico->getDsImpedimentoExecucao() : '<br />'; ?>
                </td>
            </tr>
        </table>
        <br/>
        <table style="width: 100%;" cellpadding="3" cellspacing="1">
            <tr style="background: #CCCCCC">
                <td colspan="3" align="center">
                    <strong>Sugestão de Melhorias para as Atividades ou Processos</strong>
                </td>
            </tr>
            <tr>
                <td colspan="3" align="left">
                    <?php echo ($this->ordem_servico->getDsSugestaoMelhoria()) ? $this->ordem_servico->getDsSugestaoMelhoria() : '<br />'; ?>
                </td>
            </tr>
        </table>
        <br>
        <table style="width: 100%;" cellpadding="3" cellspacing="1">
            <tr>
                <td style="width: 50%;">
                    <table style="width: 490px;" border="0">
                        <tr>
                            <td class="sem-borda"><strong>Preposto:</strong></td>
                        </tr>
                        <tr>
                            <td class="sem-borda" align="center">
                                <br/>
                                <br/>
                                <hr>
                                <p><?php echo $this->ordem_servico->getNoPreposto(); ?></p>
                            </td>
                        </tr>
                    </table>
                </td>
                <td style="width: 50%;">
                    <table style="width: 490px;" border="0">
                        <tr>
                            <td class="sem-borda"><strong>Gestor do Contrato:</strong></td>
                        </tr>
                        <tr>
                            <td class="sem-borda" align="center">
                                <br/>
                                <br/>
                                <hr>
                                <p><?php echo $this->ordem_servico->getNoGestorContrato(); ?></p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
<?php
if ($this->booQuedraPagaina) {
    ?>
    <pagebreak type="NEXT-ODD" resetpagenum="1" pagenumstyle="i" suppress="off"/>
    <?php
}
?>