<?php

use InepZend\Util\Date;

$montarRelatorioTecnico = '';
?>
<head>
    <meta http-equiv="cache-control" content="max-age=0"/>
    <meta http-equiv="cache-control" content="no-cache"/>
    <meta http-equiv="expires" content="0"/>
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT"/>
    <meta http-equiv="pragma" content="no-cache"/>
    <meta charset="UTF-8">
</head>
<style>
    .lista-demanda {
        font-weight: bold;
    }

    table {
        border-spacing: 0;
        border-collapse: collapse;
    }

    .lista-demanda li span {
        font-weight: normal;
    }

    td, th, div, p {
        font-size: 12px;
    }

    td, th {
        border: 1px solid black;
    }

    .sem-borda {
        border: 0px !important;
    }

    body {
        margin: 0px;
    }

    .page {
        width: 1000px;
        background-color: #FFFFFF;
        text-align: left;
        margin-bottom: 20px;
        padding: 10px;
    }
</style>

<?php
$montarRelatorioTecnico = function ($demanda, $arrAtividades, $intNumeroDemanda, $renderDescricaoDemanda) {
    $arrDetalhesAtividade = [];
    foreach ($arrAtividades as $arrInfoAtividade) {
        $arrDetalhesAtividade[] = $arrInfoAtividade['co_atividade'] . ' - ' . $arrInfoAtividade['no_atividade'];
    }
    ?>
    <p>&nbsp;</p>
    <li>
        <p>

        <p><strong><?php echo $intNumeroDemanda . '. ' . $demanda->getNoDemanda(); ?></strong></p>
        <br/>

        <p>
            Atividade:
        <ul>
            <?php
            foreach ($arrAtividades as $arrInfoAtividade) {
                echo '<li>' . $arrInfoAtividade['co_atividade'] . ' - ' . $arrInfoAtividade['no_atividade'] . '</li>';
            }
            ?>
        </ul>
        </p>
        <br/>

        <p>Executor: <?php echo $demanda->getNoExecutor(); ?></p>
        <br/>

        <p>Data Abertura: <?php echo $demanda->getDtAbertura(); ?></p>
        <br/>

        <p>Projeto: <?php echo ($demanda->getNoProjeto()) ? $demanda->getNoProjeto() : ' - '; ?></p>
        <br/>

        <p>Ambiente: <?php echo ($demanda->getNoProjeto()) ? $demanda->getDsAmbiente() : ' - '; ?></p>
        <br/>
        <ul>
            <li>
                <strong>Solicitação</strong>
                <br/>
                <?php echo $renderDescricaoDemanda->renderizaDescricaoImpressao(trim($demanda->getDsDescricao())); ?>
                <br/>
            </li>
            <li>
                <strong>Solução aplicada</strong>
                <br/>
                <?php echo ($demanda->getDsSolucao()) ? $renderDescricaoDemanda->renderizaDescricaoImpressao(trim($demanda->getDsSolucao())) : ' - ' ?>
            </li>
        </ul>
        </p>
    </li>
    <?php
}
?>

<div class="page">
    <table style="width: 100%;" cellpadding="3" cellspacing="1">
        <tr>
            <td class="sem-borda" align="center"><strong>RELATÓRIO TÉCNICO</strong></td>
        </tr>
    </table>
    <hr>
    <div>
        <p><strong>1. Contexto</strong></p>

        <p>Demandas referentes:</p>
        <ol class="lista-demanda">
            <?php
            $renderDescricaoDemanda = $this->renderDescricaoDemandaHelper();
            if (trim($this->ordem_servico->getDsDescricao()) == '') {
                echo $renderDescricaoDemanda->renderDescricaoDemanda($this->arrDemandas, $this->arrDemandaSuperior);
            } else
                echo '<p>' . $renderDescricaoDemanda->renderizaDescricaoImpressao($this->ordem_servico->getDsDescricao()) . '</p>';
            ?>
        </ol>
    </div>
    <br/>
    <br/>

    <div>
        <p><strong>2. Identificação</strong></p>
        <table style="width: 100%;" cellpadding="3" cellspacing="1">
            <tr>
                <td style="background: #CCCCCC; width: 300px;"><strong>N° da Ordem de Serviço (OS)</strong></td>
                <td><?php echo $this->ordem_servico->getNuOrdemServico(); ?></td>
                <td style="background: #CCCCCC; width: 200px;"><strong>Versão dos Critérios</strong></td>
                <td>V 1.0</td>
            </tr>
            <tr>
                <td style="background: #CCCCCC;"><strong>Solicitante</strong></td>
                <td colspan="3"><?php echo $this->ordem_servico->getNoFiscalRequisitante(); ?></td>
            </tr>
        </table>
    </div>
    <br/>
    <br/>

    <div>
        <p><strong>3. Registro de Mudanças</strong></p>
        <table style="width: 100%;" cellpadding="3" cellspacing="1">
            <tr style="background: #CCCCCC;">
                <td style="width: 100px;"><strong>Versão</strong></td>
                <td style="width: 100px;"><strong>Dt. Versão</strong></td>
                <td><strong>Responsável</strong></td>
                <td><strong>Motivação</strong></td>
            </tr>
            <tr>
                <td>1.0.0</td>
                <td>
                    <?php echo Date::convertDate($this->ordem_servico->getDtPrazo(), 'd/m/Y'); ?>
                </td>
                <td>
                    <?php
                    echo implode('<br />', $renderDescricaoDemanda->arrResponsavel);
                    ?>
                </td>
                <td>Criação do Documento</td>
            </tr>
        </table>
    </div>
    <br/>
    <br/>

    <div>
        <p><strong>4. Parecer Técnico</strong></p>
        <ul style="list-style-type: none;">
            <?php
            foreach ($this->arrDemandas as $mixDemanda) :
                $intPosicao = $mixDemanda['demanda']->sequencia;
//                if ($mixDemanda['demanda']->getIdDemandaSuperior()) {
//                    foreach ($mixDemanda['atividade'] as $intSequencia => $arrAtividade) {
//                        $intPosicao .= '.' . $arrAtividade['nu_sequencia'];
//                        montarRelatorioTecnico($mixDemanda['demanda'], $mixDemanda['atividade'], $intPosicao, $renderDescricaoDemanda);
//                    }
//                } else {
                $montarRelatorioTecnico($mixDemanda['demanda'], $mixDemanda['atividade'], $intPosicao, $renderDescricaoDemanda);
//                }
            endforeach;
            ?>
        </ul>
    </div>
</div>